import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import LeftSidebar from '@/components/apps-components/LeftSidebar';

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font--Poppins"
})

export const metadata: Metadata = {
  title: 'Premier League',
  description: 'Generated by Premier League',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="flex h-screen overflow-auto text-white">
          {/* this is left side bar  */}
          <div className='hidden lg:block lg:w-[4%] 2xl:w-[5%] h-full overflow-auto bg-black'>
            <LeftSidebar />
          </div>

          {/* this is right side  */}
          <div className='w-full lg:w-[96%] 2xl:w-[95%] bg-bgBlack h-full overflow-auto'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
