import type { Metadata } from 'next'
import SoccerNavbar from './SoccerNavbar'

export const metadata: Metadata = {
    title: 'Premier League - Soccer',
    description: 'Generated by Premier League',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div className='h-full'>
            <SoccerNavbar />
            <div className='h-full'>
                {children}
            </div>
        </div>
    )
}
